# $OpenBSD$

COMMENT =		library for elliptic curves cryptography

GH_COMMIT =		934a31ab20c4c52c0b50469ac6be32e72b5187f1
GH_ACCOUNT =		ANSSI-FR
GH_PROJECT =		libecc
DISTNAME =		libecc-0.20170517

CATEGORIES =		math

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# Dual BSD / GPLv2
PERMIT_PACKAGE_CDROM =	Yes

USE_GMAKE =		Yes

.include <bsd.port.mk>
