# $OpenBSD$

COMMENT =	Easily timeout long running operations

DISTNAME =	Time-Out-0.11
CATEGORIES =	devel

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

.include <bsd.port.mk>
