
COMMENT =		simulate electronic circuit using Python and Ngspice

MODPY_EGG_VERSION = 	1.5
DISTNAME =		PySpice-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}
CATEGORIES =		cad

HOMEPAGE =		https://github.com/PySpice-org/PySpice

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# GPLv3
PERMIT_PACKAGE =	Yes

MODULES =		lang/python
MODPY_SETUPTOOLS =	Yes
MODPY_PI =		Yes

FLAVORS =		python3
FLAVOR =		python3

NO_TEST =		Yes

.include <bsd.port.mk>
