# $OpenBSD$

COMMENT =	information about the phase of the Moon

DISTNAME =	Astro-MoonPhase-0.60
CATEGORIES =	astro

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Public Domain
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =		cpan

USE_GROFF =		Yes

.include <bsd.port.mk>
