# $OpenBSD$

COMMENT =	information about the phase of the Moon

DISTNAME =	Astro-MoonPhase-0.60
CATEGORIES =	astro

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Public Domain
PERMIT_PACKAGE =	Yes

MODULES =		cpan

.include <bsd.port.mk>
