# $OpenBSD$

COMMENT =	perl extension for parsing FR street addresses

DISTNAME =	Geo-StreetAddress-FR-0.0.4
CATEGORIES =	geo

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-Class-Accessor
REGRESS_DEPENDS =	devel/p5-Test-Perl-Critic

USE_GROFF =		Yes

.include <bsd.port.mk>
