# $OpenBSD: Makefile,v 1.20 2014/06/14 23:24:58 sthen Exp $

SHARED_ONLY=	Yes

COMMENT=	interface for cyclic redundancy check generation

MODULES=	cpan
DISTNAME =	String-CRC32-1.5
CATEGORIES=	devel

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Public domain
PERMIT_PACKAGE_CDROM=   Yes

WANTLIB += c

.include <bsd.port.mk>
