
COMMENT = 	Perl functions to compare Git versions

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	Git-Version-Compare-1.004
CATEGORIES =	devel

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# perl
PERMIT_PACKAGE =	Yes

TEST_DEPENDS =	devel/p5-Test-NoWarnings

.include <bsd.port.mk>
