# $OpenBSD$

COMMENT =	flashing utility for STM32 and STM32W through UART or I2C

DISTNAME =	stm32flash-0.4.150320
CATEGORIES =	devel

HOMEPAGE =	https://code.google.com/p/stm32flash/

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# GPLv2
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB +=	c

MASTER_SITES =	http://www.arcane-labs.net/download/OpenBSD/

NO_TEST =	Yes

.include <bsd.port.mk>
