
COMMENT =	flashing utility for STM32 and STM32W through UART or I2C

DISTNAME =	stm32flash-0.7
CATEGORIES =	devel

HOMEPAGE =	https://sourceforge.net/projects/stm32flash/

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# GPLv2
PERMIT_PACKAGE =	Yes

WANTLIB +=	c

# MASTER_SITES =	https://www.arcane-labs.net/download/OpenBSD/
SITES =		${SITE_SOURCEFORGE:=stm32flash/}

USE_GMAKE =	Yes

NO_TEST =	Yes

.include <bsd.port.mk>
