# $OpenBSD: Makefile,v 1.10 2013/03/11 11:35:52 espie Exp $

COMMENT=	Perl interface to the DICT protocol

MODULES=	cpan
DISTNAME =	Net-Dict-2.19
CATEGORIES=	net

MAINTAINER=	Sam Smith <s@msmith.net>

# GPL/Artistic License
PERMIT_PACKAGE_CDROM=	Yes

RUN_DEPENDS=	devel/p5-AppConfig-Std

TEST_DEPENDS = devel/p5-Test-Differences

.include <bsd.port.mk>
