
COMMENT =	perl portable interface to open and send raw data to network 

DISTNAME =	Net-Write-1.05
CATEGORIES =	net

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl Artistic License
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan
         
MODCPAN_EXAMPLES =	Yes

BUILD_DEPENDS =		${RUN_DEPENDS}
RUN_DEPENDS =		devel/p5-Class-Gomor \
			net/p5-Net-Pcap \
			net/p5-Socket6
                                                
.include <bsd.port.mk>
