# $OpenBSD: Makefile,v 1.9 2013/10/11 23:51:20 naddy Exp $

COMMENT=	converts simple text to web constructs

DISTNAME =	Text-Textile-2.13
CATEGORIES=	textproc

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

HOMEPAGE =	https://github.com/bradchoate/text-textile/

# Perl
PERMIT_PACKAGE_CDROM=	Yes

MODULES=	cpan

.include <bsd.port.mk>
