# $OpenBSD$

COMMENT =	another class and object builder in Perl 

DISTNAME =	Class-Gomor-1.02
CATEGORIES =	devel

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl Artistic License
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =		cpan
         
MODCPAN_EXAMPLES =	Yes

.include <bsd.port.mk>
