# $OpenBSD$

COMMENT =	read/write/modify Perl/XS typemap files

DISTNAME =	ExtUtils-Typemap-0.05
CATEGORIES =	devel

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =		cpan

USE_GROFF =		Yes

.include <bsd.port.mk>
