# $OpenBSD$

SHARE_ONLY =	Yes

COMMENT =	high resolution alarm, sleep, gettimeofday, interval timers

DISTNAME =	Time-HiRes-1.9726
CATEGORIES =	devel

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

.include <bsd.port.mk>
