# $OpenBSD: Makefile,v 1.8 2011/03/14 09:17:26 sthen Exp $

COMMENT=	pager utility

DISTNAME=	Data-Pageset-1.06
REVISION=	0
CATEGORIES=	databases
MODULES=	cpan
USE_GROFF =	Yes

# Perl
PERMIT_PACKAGE_CDROM=	Yes

RUN_DEPENDS=	databases/p5-Data-Page

.include <bsd.port.mk>
