
COMMENT =		API/framework for generating random, malformed data

DISTNAME =		antiparser-2.0

CATEGORIES =		security

HOMEPAGE =		http://www.antiparser.org/

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# GPLv2
PERMIT_PACKAGE_CDROM =	Yes

SITES =			${SITE_SOURCEFORGE:=antiparser/}

MODULES =		lang/python

.include <bsd.port.mk>
