# $OpenBSD$

COMMENT =	Validate your CPAN META.yml files

DISTNAME =	Test-CPAN-Meta-0.23
CATEGORIES =	devel

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

.include <bsd.port.mk>
