
COMMENT =		module for using fake objects to test real ones

MODPY_EGG_VERSION =	1.0.3
DISTNAME =		fudge-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}

CATEGORIES =		devel

HOMEPAGE =		http://farmdev.com/projects/fudge/

# MIT
PERMIT_PACKAGE =		Yes

SITES=			${SITE_PYPI:=f/fudge/}

MODULES =		lang/python

MODPY_SETUPTOOLS =	Yes
NO_TEST =		Yes

.include <bsd.port.mk>
