# $OpenBSD$

COMMENT =		lightweight regexp-based XML parser

DISTNAME =		XML-Parser-Lite-0.72
CATEGORIES =		textproc

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

.include <bsd.port.mk>
