
COMMENT =	portable 6809 cross-assembler

V =		2.12
DISTNAME =	asm6809-${V}
CATEGORIES =	devel

HOMEPAGE =	https://www.6809.org.uk/asm6809/dl/

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# GPLv3
PERMIT_PACKAGE =	Yes

WANTLIB +=		c

SITES =                 https://www.6809.org.uk/asm6809/dl/

CONFIGURE_STYLE =	gnu

TEST_TARGET=	check

.include <bsd.port.mk>
