# $OpenBSD$

COMMENT =	An object for all network related stuff 

DISTNAME =	Net-Packet-Target-1.01
CATEGORIES =	net

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl artistic license
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

BUILD_DEPENDS =		${RUN_DEPENDS}
RUN_DEPENDS =		devel/p5-Class-Gomor \
			net/p5-Net-Packet
  
MODCPAN_EXAMPLES =	Yes

.include <bsd.port.mk>
