
COMMENT =		remote Shell for MicroPython

MODPY_EGG_VERSION =	20220518
DISTNAME =		rshell-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}

CATEGORIES =		sysutils

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# MIT
PERMIT_PACKAGE =	Yes

GH_ACCOUNT =    	dhylands
GH_PROJECT =    	rshell
GH_COMMIT =		b87878c01aa02d6cd871ff4666983dee5584af16

MODULES =		lang/python

FLAVORS =		python3
FLAVOR =		python3

MODPY_SETUPTOOLS =	Yes

NO_TEST =		Yes
                
.include <bsd.port.mk>
