
COMMENT =		remote Shell for MicroPython

MODPY_EGG_VERSION =	20241204
DISTNAME =		rshell-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}

CATEGORIES =		sysutils

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# MIT
PERMIT_PACKAGE =	Yes

GH_ACCOUNT =    	dhylands
GH_PROJECT =    	rshell
GH_COMMIT =		7441a2529149f3bdee64503d4412416b8387c8f3

MODULES =		lang/python

MODPY_PYBUILD =		setuptools

NO_TEST =		Yes
                
.include <bsd.port.mk>
