# $OpenBSD$

COMMENT =		pure Python library for PNG image encoding/decoding

MODPY_EGG_VERSION =	0.0.18
DISTNAME =		pypng-${MODPY_EGG_VERSION}
PKGNAME =		py-png-${MODPY_EGG_VERSION}
CATEGORIES =		graphics

HOMEPAGE =		https://github.com/drj11/pypng

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# MIT
PERMIT_PACKAGE_CDROM =	Yes

MODPY_PI =		Yes

MODULES =		lang/python

MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
