# $OpenBSD$

COMMENT =		manipulate data from Intel HEX file format

MODPY_EGG_VERSION = 	2.2.1
DISTNAME =		intelhex-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}
CATEGORIES =		devel

HOMEPAGE =		https://pypi.org/project/IntelHex/

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# BSD
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes

NO_TEST =		Yes

.include <bsd.port.mk>
