# $OpenBSD$

COMMENT =	compare difference between numbers against a given tolerance

DISTNAME =	Test-Number-Delta-1.06
CATEGORIES =	devel

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Apache 2
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

.include <bsd.port.mk>
