
COMMENT =	perl interface to libnova 

DISTNAME =	Astro-Nova-0.07
CATEGORIES =	astro

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

#BUILD_DEPENDS =		devel/p5-ExtUtils-Typemap
#RUN_DEPENDS =		${BUILD_DEPENDS}

CONFIGURE_STYLE =	modbuild

MODCPAN_EXAMPLES =	Yes

.include <bsd.port.mk>
