
COMMENT =		python SMB Password Hash Generator 

MODPY_EGG_VERSION =	1.0.1
DISTNAME =		py-smbpasswd-${MODPY_EGG_VERSION}

CATEGORIES =		security

HOMEPAGE =		http://barryp.org/software/py-smbpasswd/

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# GPLv2
PERMIT_PACKAGE_CDROM =	Yes

SITES =			http://barryp.org/static/software/download/py-smbpasswd/1.0.1/

MODULES =		lang/python

.include <bsd.port.mk>
