# $OpenBSD$

COMMENT =		Automatic hostnames and virtual hosts discovery tool

DISTNAME =		hostmap-0.2
CATEGORIES =		security

HOMEPAGE =		http://hostmap.sourceforge.net/

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# GPLv3
PERMIT_PACKAGE_CDROM =	Yes

MASTER_SITES =		${MASTER_SITE_SOURCEFORGE:=hostmap/}

MODULES =		lang/ruby

#BUILD_DEPENDS =	::devel/ruby-rake
#RUN_DEPENDS =		::devel/ruby-rake

NO_BUILD =		Yes
NO_TEST =		Yes

PKG_ARCH =		*

.include <bsd.port.mk>
