# $OpenBSD$

COMMENT =	assorted astronomical routines

DISTNAME =	Astro-0.73
CATEGORIES =	astro

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

USE_GROFF =		Yes

.include <bsd.port.mk>
