
COMMENT =	assorted astronomical routines

DISTNAME =	Astro-0.73
CATEGORIES =	astro

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

.include <bsd.port.mk>
