# $OpenBSD$

COMMENT =	a general-purpose iterator class.

DISTNAME =	Iterator-0.03
CATEGORIES =	devel

CPAN_AUTHOR =	ROODE

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =		cpan

REGRESS_DEPENDS =	devel/p5-Exception-Class

.include <bsd.port.mk>
