# $OpenBSD$

COMMENT =	perl extension for fast Galois Field arithmetic

DISTNAME =	Math-FastGF2-0.04
CATEGORIES =	math

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# GPLv2 - LPGLv2
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =		cpan

USE_GROFF =		Yes

.include <bsd.port.mk>
