# $OpenBSD$

COMMENT =	perl extension for fast Galois Field arithmetic

DISTNAME =	Math-FastGF2-0.07
CATEGORIES =	math

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# GPLv2 - LPGLv2
PERMIT_PACKAGE =	Yes

MODULES =		cpan

#USE_GROFF =		Yes

.include <bsd.port.mk>
