
COMMENT =	perl Framework to easily send and receive frames

DISTNAME =	Net-Packet-3.27
CATEGORIES =	net

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

BUILD_DEPENDS =		${RUN_DEPENDS}
RUN_DEPENDS =		math/p5-Bit-Vector \
			net/p5-Net-IPv4Addr \
			net/p5-Net-IPv6Addr \
			net/p5-Net-Write \
			net/p5-Net-Libdnet \
			devel/p5-Class-Gomor
         
MODCPAN_EXAMPLES =	Yes

.include <bsd.port.mk>
