# $OpenBSD$

COMMENT =		yara-python extension

MODPY_EGG_VERSION =	1.6
DISTNAME =		yara-python-${MODPY_EGG_VERSION}
PKGNAME =		py-yara-${MODPY_EGG_VERSION}

CATEGORIES =		security

HOMEPAGE =		http://code.google.com/p/yara-project/

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# GPLv2
PERMIT_PACKAGE_CDROM =	Yes

MASTER_SITES =		http://yara-project.googlecode.com/files/

LIB_DEPENDS =		security/yara

MODULES =		lang/python

NO_TEST =		Yes

.include <bsd.port.mk>
