# $OpenBSD$

COMMENT =		a freeware C compiler for 6502 based systems

DISTNAME =		cc65-20160317
CATEGORIES =		devel

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# BSD
PERMIT_PACKAGE_CDROM =	Yes

MASTER_SITES =		${MASTER_SITES_GITHUB}

HOMEPAGE =		https://github.com/cc65/wiki/wiki

GH_ACCOUNT =		cc65
GH_PROJECT =		cc65
GH_COMMIT =		78dcb61cb8d59efa93ac8d5cb4fa08598553121a

WANTLIB +=		c m

USE_GMAKE =		Yes

NO_TEST =		Yes

.include <bsd.port.mk>
