
COMMENT =	displaying waveforms for different HDL simulators

MODPY_EGG_VERSION =	1.0.6
DISTNAME =	wavedisp-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	sysutils

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# GPLv3
PERMIT_PACKAGE =	Yes

GH_ACCOUNT =    cclienti
GH_PROJECT =    wavedisp
GH_COMMIT =	66bc7909638891fa34afe8af21c61acaa6e4eb91

MODULES =	lang/python
MODPY_SETUPTOOLS = Yes

FLAVORS =	python3
FLAVOR ?=	python3

NO_TEST =	Yes

.include <bsd.port.mk>
