# $OpenBSD$

COMMENT =	dynamic class mixing

DISTNAME =	Class-Mix-0.004
CATEGORIES =	devel

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =		cpan

USE_GROFF =		Yes

RUN_DEPENDS =		devel/p5-Params-Classify

CONFIGURE_STYLE =	modbuild

.include <bsd.port.mk>
