
COMMENT =		helper to test command-line scripts

MODPY_EGG_VERSION =	1.2
DISTNAME =		ScriptTest-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}

CATEGORIES =		devel

HOMEPAGE =		http://bitbucket.org/ianb/scripttest/

# MIT
PERMIT_PACKAGE =		Yes

SITES =			${SITE_PYPI:=S/ScriptTest/}

MODULES =		lang/python

MODPY_SETUPTOOLS =	Yes

NO_TEST =		Yes

.include <bsd.port.mk>
