# $OpenBSD$

COMMENT =		an SSL Cipher scanner
DISTNAME =		athena-ssl-cipher-check_v062
PKGNAME =		athena-ssl-cipher-check-v062
CATEGORIES =		security

HOMEPAGE =		http://dmcdonald.net/

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# GPLv3
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

MASTER_SITES =		${HOMEPAGE}

MODULES =		java
MODJAVA_VER =		1.3+

NO_REGRESS =		Yes

.include <bsd.port.mk>
