
COMMENT =		framework/API for generating random, malformed data

MODPY_EGG_VERSION =	0.2
DISTNAME =		arc4-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}

CATEGORIES =		security

HOMEPAGE =		http://mitya.paunix.org/src/py-arc4

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# BSD
PERMIT_PACKAGE_CDROM =	Yes

SITES =			${SITE_PYPI:=a/arc4/}

MODULES =		lang/python

.include <bsd.port.mk>
