# $OpenBSD$

COMMENT =	perl binding for Redis database

DISTNAME =	Redis-1.2001
CATEGORIES =	databases

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =		cpan

USE_GROFF =		Yes

.include <bsd.port.mk>
