# $OpenBSD: Makefile,v 1.13 2013/03/11 11:35:53 espie Exp $

COMMENT=		perl5 module for interactive network functions

MODULES=		cpan
DISTNAME =		Net-Telnet-3.04
CATEGORIES=		net

# Perl
PERMIT_PACKAGE_CDROM=	Yes

MAINTAINER=		Nick Nauwelaerts <nick@nauwelaerts.net>

.include <bsd.port.mk>
