
COMMENT =	does your process have access to the web

DISTNAME =	LWP-Online-1.08
CATEGORIES =	www

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		www/p5-URI \
			www/p5-libwww

.include <bsd.port.mk>
