# $OpenBSD$

CATEGORIES ?=		security

HOMEPAGE ?=		http://www.openvas.org/

MAINTAINER ?=		Nigel Taylor <njtaylor@asterisk.demon.co.uk>

MASTER_SITES_OPENVAS =	http://wald.intevation.org/frs/download.php/

# GPLv2+
PERMIT_PACKAGE_CDROM ?=	Yes

USE_LIBTOOL ?=		Yes
