# $OpenBSD$

COMMENT =		python Dragon emulator

MODPY_EGG_VERSION = 	0.7.0
DISTNAME =		DragonPy-${MODPY_EGG_VERSION}pl201001
CATEGORIES =		emulators

HOMEPAGE =		https://github.com/jedie/DragonPy

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# GPLv3
PERMIT_PACKAGE =	Yes

GH_ACCOUNT =		jedie
GH_PROJECT =		DragonPy
GH_COMMIT =		0cac1cdfe27094a5af3ac8c8f9a06a49b2b97826

MODULES =		lang/python

# pip install DragonPyEmulator
#MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes

FLAVORS =		python3
FLAVOR =		python3

.include <bsd.port.mk>
