# $OpenBSD$

COMMENT =	test a Pod's content

DISTNAME =	Test-Pod-Content-v0.0.6
PKGNAME =	p5-${DISTNAME:S/v//}
CATEGORIES =	devel

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

CONFIGURE_STYLE =	modbuild

.include <bsd.port.mk>
