
COMMENT =		python filter design analysis tool

MODPY_EGG_VERSION =     0.9.5
GH_ACCOUNT =    	chipmuenk
GH_PROJECT =    	pyfda
GH_TAGNAME =		v${MODPY_EGG_VERSION}

CATEGORIES =		cad

HOMEPAGE =		https://github.com/chipmuenk/pyfda

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# GPLv3
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PYBUILD =		setuptools

RUN_DEPENDS =		graphics/py-matplotlib \
			math/py-numpy \
			math/py-numexpr \
			math/py-scipy \
			textproc/py-markdown \
			x11/py-qt5

NO_TEST =		Yes

.include <bsd.port.mk>
