# $OpenBSD$

COMMENT =	minimal serial ports library

DISTNAME =	libserialport-0.1.1
MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

SHARED_LIBS =	serialport	0.0	# 1.0

CATEGORIES =	comms

HOMEPAGE =	https://sigrok.org/wiki/Libserialport
MASTER_SITES =	http://sigrok.org/download/source/libserialport/

# LGPLv3
PERMIT_PACKAGE_CDROM =	Yes

CONFIGURE_STYLE =	gnu

.include <bsd.port.mk>
