
COMMENT =		ELF reader-writer library for Python3

MODPY_EGG_VERSION = 	0.3.4
DISTNAME =		makeelf-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}
CATEGORIES =		sysutils

HOMEPAGE =		https://github.com/v3l0c1r4pt0r/makeelf

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# GPLv3
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes

FLAVORS =		python3
FLAVOR =		python3

NO_TEST =		Yes

.include <bsd.port.mk>
