# $OpenBSD$

COMMENT =	details of the floating point data type

DISTNAME =	Data-Float-0.011
CATEGORIES =	math

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

USE_GROFF =		Yes

CONFIGURE_STYLE =	modbuild

.include <bsd.port.mk>
