# $OpenBSD$

COMMENT =	access CP/M file systems

DISTNAME =	cpmtools-2.21
MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

CATEGORIES =	sysutils

HOMEPAGE =	http://www.moria.de/~michael/cpmtools/
MASTER_SITES =	http://www.moria.de/~michael/cpmtools/files/

# GPLv3
PERMIT_PACKAGE =	Yes

WANTLIB +=		c curses

CONFIGURE_STYLE =	gnu

NO_TEST =		Yes

.include <bsd.port.mk>
