# $OpenBSD$

COMMENT =	access CP/M file systems

DISTNAME =	cpmtools-2.20
MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

CATEGORIES =	sysutils

HOMEPAGE =	http://www.moria.de/~michael/cpmtools/
MASTER_SITES =	http://www.moria.de/~michael/cpmtools/files/

# GPLv3
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB +=		c

CONFIGURE_STYLE =	gnu

.include <bsd.port.mk>
