# $OpenBSD$

COMMENT =		

DISTNAME =		battalion1.4b
PKGNAME =		battalion-1.4b
CATEGORIES =		games

HOMEPAGE =		http://www.evl.uic.edu/aej/AndyBattalion.html

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# 
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MASTER_SITES =		http://www.evl.uic.edu/aej/BATTALION/

EXTRACT_SUFX =		.tar.bz2

NO_REGRESS =		Yes

.include <bsd.port.mk>
