
COMMENT =		

DISTNAME =		battalion1.4b
PKGNAME =		battalion-1.4b
CATEGORIES =		games

HOMEPAGE =		http://www.evl.uic.edu/aej/AndyBattalion.html

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# 
PERMIT_PACKAGE_CDROM =	Yes

SITES =			http://www.evl.uic.edu/aej/BATTALION/

EXTRACT_SUFX =		.tar.bz2

NO_TEST =		Yes

.include <bsd.port.mk>
