# $OpenBSD$

COMMENT =	the Eksblowfish block cipher

DISTNAME =	Crypt-Eksblowfish-0.008
CATEGORIES =	security

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-Class-Mix

USE_GROFF =		Yes

CONFIGURE_STYLE =	modbuild

.include <bsd.port.mk>
