
COMMENT =		recover deleted files from FAT filesystems
DISTNAME =		fatback-1.3
CATEGORIES =		sysutils
HOMEPAGE =		http://fatback.sourceforge.net
MAINTAINER =		Dmitri Alenichev <mitya@sdf.lonestar.org>

# GPLv2
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB =		c
SITES =			${SITE_SOURCEFORGE:=fatback/}
CONFIGURE_STYLE =	gnu

.include <bsd.port.mk>
