# $OpenBSD$

COMMENT =		recover deleted files from FAT filesystems
DISTNAME =		fatback-1.3
CATEGORIES =		sysutils
HOMEPAGE =		http://fatback.sourceforge.net
MAINTAINER =		Dmitri Alenichev <mitya@sdf.lonestar.org>

# GPLv2
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

WANTLIB =		c
MASTER_SITES =		${MASTER_SITE_SOURCEFORGE:=fatback/}
CONFIGURE_STYLE =	gnu

.include <bsd.port.mk>
