# $OpenBSD$

COMMENT =	cloud storage client library

DISTNAME =	Droplet
CATEGORIES =	devel

HOMEPAGE =	http://github.com/scality/Droplet/wiki

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# BSD
PERMIT_PACKAGE_CDROM =		Yes
PERMIT_PACKAGE_FTP =		Yes
PERMIT_DISTFILES_CDROM =	Yes
PERMIT_DISTFILES_FTP =		Yes

WANTLIB =		c

MASTER_SITES =		https://github.com/scality/Droplet.git

AUTOCONF_VERSION =	2.59
AUTOMAKE_VERSION =	1.9

CONFIGURE_STYLE =	autoconf automake

.include <bsd.port.mk>
