# $OpenBSD$

COMMENT =		a lean disassembler targeting small architectures

DISTNAME =		ucdisasm-20130609
CATEGORIES =		devel

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# GPLv3
PERMIT_PACKAGE =	Yes

MASTER_SITES =		${MASTER_SITES_GITHUB}

HOMEPAGE =		https://github.com/edma2/ucdisasm

GH_ACCOUNT =		edma2
GH_PROJECT =		ucdisasm
GH_COMMIT =		eb98deb864a851af76329af5803536215e396068

WANTLIB +=		c

USE_GMAKE =		Yes

# python2 && avr-binutils need
#NO_TEST =		Yes

.include <bsd.port.mk>
