# $OpenBSD$

COMMENT =		crc generator

MODPY_EGG_VERSION = 	1.7
DISTNAME =		crcmod-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}
CATEGORIES =		devel

HOMEPAGE =		http://crcmod.sourceforge.net/

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes

NO_TEST =		Yes

.include <bsd.port.mk>
