
COMMENT =		BCH library C Python module 

MODPY_EGG_VERSION = 	0.14.0
DISTNAME =		bchlib-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}
CATEGORIES =		math

HOMEPAGE =		https://github.com/jkent/python-bchlib

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# GPLv2
PERMIT_PACKAGE =	Yes

MODULES =		lang/python
MODPY_SETUPTOOLS =	Yes
MODPY_PI =		Yes

FLAVORS =		python3
FLAVOR =		python3

.include <bsd.port.mk>
