# $OpenBSD$

COMMENT =		???

DISTNAME =		ufoai-2.2.1-source
PKGNAME =		${DISTNAME:S/-source//}
CATEGORIES =		games

HOMEPAGE =		http://ufoai.sourceforge.net/

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# GPL
PERMIT_PACKAGE_CDROM =	Yes

#WANTLIB =		???

MASTER_SITES =		${MASTER_SITE_SOURCEFORGE:=ufoai/}
EXTRACT_SUFX =		.tar.bz2

USE_GROFF =		Yes
USE_GMAKE =		Yes

CONFIGURE_STYLE =	gnu

NO_TEST =		Yes

.include <bsd.port.mk>
