# $OpenBSD$

COMMENT =		Fairly Secure Hashed Password

MODPY_EGG_VERSION =	0.2.1
DISTNAME =		fshp-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}

CATEGORIES =		security

HOMEPAGE =		http://pypi.python.org/pypi/fshp/

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# Public Domain
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MASTER_SITES =		${MASTER_SITE_PYPI:=f/fshp/}

MODULES =		lang/python

NO_REGRESS =		Yes

.include <bsd.port.mk>
