# $OpenBSD$

COMMENT =		Compendium for OpenVAS
DISTNAME =		openvas-compendium-1.0.1

BROKEN =		Work in progress

MASTER_SITES =		${MASTER_SITES_OPENVAS:=558/}


USE_LIBTOOL =		No

.include <bsd.port.mk>
