# $OpenBSD: Makefile,v 1.3 2010/12/03 11:46:50 ajacoutot Exp $

COMMENT=	lightweight, 'relaxed' RSS (and XML-ish) parser

MODULES=	cpan
DISTNAME=	XML-RSSLite-0.15
CATEGORIES=	textproc
EXTRACT_SUFX=	.tgz
USE_GROFF =	Yes

MAINTAINER=	Simon Bertrang <simon@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
