# $OpenBSD: Makefile,v 1.5 2013/10/11 23:51:24 naddy Exp $

COMMENT=	lightweight, 'relaxed' RSS (and XML-ish) parser

MODULES=	cpan
DISTNAME =	XML-RSSLite-0.15
CATEGORIES=	textproc

# Perl
PERMIT_PACKAGE_CDROM=	Yes

EXTRACT_SUFX = 		.tgz

.include <bsd.port.mk>
