# $OpenBSD$

COMMENT =		GTP ping

DISTNAME =		gtping-0.14
CATEGORIES =		net

HOMEPAGE =		http://www.habets.pp.se/synscan/programs.php?prog=gtping

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# GPLv2
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

WANTLIB =		c m

MASTER_SITES =		http://www.habets.pp.se/synscan/files/ \
			http://www.arcane-labs.net/download/OpenBSD/

USE_GROFF =		Yes

CONFIGURE_STYLE =	gnu

NO_REGRESS =		Yes

.include <bsd.port.mk>
