
COMMENT =	yet another signify tool

DISTNAME =	asignify-1.0
CATEGORIES =	security

HOMEPAGE =	https://github.com/vstakhov/asignify

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# BSD
PERMIT_PACKAGE_CDROM =	Yes

GH_ACCOUNT =	vstakhov
GH_PROJECT =	asignify
GH_COMMIT =	fac8a33db071d6774084deac9f9f38c450cbf0fc

#CONFIGURE_STYLE = gnu
#NO_TEST=	Yes

.include <bsd.port.mk>
