# $OpenBSD$

COMMENT =		???

DISTNAME =		skulltag-

CATEGORIES =		games

HOMEPAGE =		http://skulltag.net/

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

#
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

WANTLIB =		???

MASTER_SITES =		???

NO_REGRESS =		Yes

.include <bsd.port.mk>
