# $OpenBSD$

COMMENT =		???

DISTNAME =		skulltag-

CATEGORIES =		games

HOMEPAGE =		http://skulltag.net/

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

#
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB =		???

MASTER_SITES =		???

NO_TEST =		Yes

.include <bsd.port.mk>
