# $OpenBSD: Makefile,v 1.21 2015/01/21 06:13:48 bentley Exp $

COMMENT =	module to determine the size of images in several formats

DISTNAME =	Image-Size-3.300
CATEGORIES =	graphics 

HOMEPAGE =	http://www.blackperl.com/Image::Size/

# Artistic License and LGPLv2
PERMIT_PACKAGE_CDROM =	Yes

MODULES =	cpan

TEST_DEPENDS =	devel/p5-Test-Pod \
		devel/p5-Test-Pod-Coverage

.include <bsd.port.mk>
