
COMMENT =	perl implementation of RIPE whois

DISTNAME =	Net-Whois-RIPE-2.006
CATEGORIES =	net

EPOCH =		1

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-Iterator-Util
                         
.include <bsd.port.mk>
