# $OpenBSD: Makefile,v 1.15 2013/05/31 04:45:10 benoit Exp $

COMMENT =	perl implementation of RIPE whois

DISTNAME =	Net-Whois-RIPE-2.004001
CATEGORIES =	net

EPOCH =		0

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-Iterator-Util
                         
.include <bsd.port.mk>
