# $OpenBSD: Makefile,v 1.6 2010/12/03 11:46:47 ajacoutot Exp $

SHARED_ONLY =	Yes

COMMENT = 	interface to the Serpent encryption algorithm

DISTNAME =	Crypt-Serpent-1.01
CATEGORIES =	security

REVISION =	3

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =	cpan

.include <bsd.port.mk>
