# $OpenBSD$

COMMENT =	multi-platform, multi-architecture disassembly framework

DISTNAME =	capstone-2.0
CATEGORIES =	devel

HOMEPAGE =	http://www.capstone-engine.org/

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# BSD
PERMIT_PACKAGE_CDROM =	Yes

MASTER_SITES = 		http://capstone-engine.org/download/2.0/

USE_GMAKE =		Yes
FAKE_FLAGS =		PREFIX=${PREFIX}

NO_TEST =		Yes

.include <bsd.port.mk>
