# $OpenBSD: Makefile,v 1.15 2013/03/11 01:30:27 espie Exp $

SHARED_ONLY=	Yes

COMMENT=	interface to the uulib library

DISTNAME =	Convert-UUlib-1.4
EPOCH =		1
CATEGORIES=	converters
MODULES=	cpan

MAINTAINER=	Ibrahim Khalifa <ibo@toontown.org>

# Perl
PERMIT_PACKAGE_CDROM=	Yes

WANTLIB += c

.include <bsd.port.mk>
