
COMMENT =		???

DISTNAME =		kulic-1.1
CATEGORIES =		games

HOMEPAGE =		http://hippo.nipax.cz/download.en.php

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# GPLv2
PERMIT_PACKAGE_CDROM =	Yes

SITES =			http://hippo.nipax.cz/src/

LIB_DEPENDS =		graphics/jpeg \
			games/allegro

USE_GROFF =		Yes
USE_GMAKE =		Yes

CONFIGURE_STYLE =	gnu

NO_TEST =		Yes

.include <bsd.port.mk>
