# $OpenBSD$

COMMENT =		Efficiently compute Skein hashes

MODPY_EGG_VERSION =	0.5
DISTNAME =		pyskein-${MODPY_EGG_VERSION}
PKGNAME =		py-skein-${MODPY_EGG_VERSION}

CATEGORIES =		security

HOMEPAGE =		http://packages.python.org/pyskein

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# GPLv3
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MASTER_SITES =		${MASTER_SITE_PYPI:=p/pyskein/}

MODULES =		lang/python
#MODPY_SETUPTOOLS =	Yes

.include <bsd.port.mk>
