# $OpenBSD: Makefile,v 1.3 2014/12/22 21:05:02 benoit Exp $

COMMENT =	PerlIO layer that adds read & write timeout to a handle

DISTNAME =	PerlIO-via-Timeout-0.29
CATEGORIES =	devel

REVISION =	1

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

TEST_DEPENDS =		net/p5-Test-TCP

.include <bsd.port.mk>
