# $OpenBSD$

COMMENT =		Python implementation of ECDSA cryptography

MODPY_EGG_VERSION = 	0.10
DISTNAME = 		ecdsa-${MODPY_EGG_VERSION}
PKGNAME = 		py-${DISTNAME}
CATEGORIES = 		security

HOMEPAGE = 		https://github.com/warner/python-ecdsa

MAINTAINER = 		Benoit Lecocq <benoit@openbsd.org>

# MIT
PERMIT_PACKAGE_CDROM = 	Yes

MASTER_SITES =		${MASTER_SITE_PYPI:=e/ecdsa/}

MODULES =		lang/python

NO_TEST =		Yes
        
.include <bsd.port.mk>
