# $OpenBSD$

COMMENT =	Bandwidth measurement tool.
DISTNAME =	bwping-1.1
PKGNAME =	${DISTNAME}
CATEGORIES =	net
HOMEPAGE =	http://bwping.sourceforge.net/

# BSD
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

WANTLIB =	c
MASTER_SITES =	${MASTER_SITE_SOURCEFORGE:=bwping/}
MAINTAINER =	Federico Fazzi <ocredef@gmail.com>

AUTOCONF_VERSION =	2.59
CONFIGURE_STYLE =	autoconf

.include <bsd.port.mk>
