# $OpenBSD$

COMMENT =	Bandwidth measurement tool.

DISTNAME =	bwping-2.2
PKGNAME =	${DISTNAME}
CATEGORIES =	net

HOMEPAGE =	http://bwping.sourceforge.net/

# BSD
PERMIT_PACKAGE =	Yes

WANTLIB =	c

MASTER_SITES =	${MASTER_SITE_SOURCEFORGE:=bwping/}

MAINTAINER =	Federico Fazzi <ocredef@gmail.com>

AUTOCONF_VERSION =	2.68
CONFIGURE_STYLE =	autoconf

.include <bsd.port.mk>
