# $OpenBSD$

COMMENT = 	check your test against the available version of Git

MODULES =	cpan
PKG_ARCH =	*
DISTNAME =	Test-Requires-Git-1.007
CATEGORIES =	devel

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# perl
PERMIT_PACKAGE_CDROM =	Yes

RUN_DEPENDS =	devel/p5-Git-Version-Compare
TEST_DEPENDS =	devel/git

.include <bsd.port.mk>
