# $OpenBSD$

COMMENT =		tool to audit PKCS12 files passwords

DISTNAME =		crackpkcs12-0.2.11
CATEGORIES =		security

HOMEPAGE =		http://crackpkcs12.sourceforge.net/

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# GPLv3
PERMIT_PACKAGE =	Yes

WANTLIB =		c crypto pthread

MASTER_SITES =		${MASTER_SITE_SOURCEFORGE:=crackpkcs12/}

CONFIGURE_STYLE =	gnu

NO_TEST =		Yes

.include <bsd.port.mk>
