# $OpenBSD$

COMMENT =		python VISA bindings

MODPY_EGG_VERSION =	1.10.1
DISTNAME =		PyVISA-${MODPY_EGG_VERSION}
PKGNAME =		py-VISA-${MODPY_EGG_VERSION}
CATEGORIES =		sysutils

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

HOMEPAGE =		https://github.com/pyvisa/pyvisa

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_VERSION =		${MODPY_DEFAULT_VERSION_3}

.include <bsd.port.mk>
