# $OpenBSD$

COMMENT =	argument type classification 

DISTNAME =	Params-Classify-0.013
CATEGORIES =	devel

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

MODULES =		cpan

USE_GROFF =		Yes

CONFIGURE_STYLE =	modbuild

.include <bsd.port.mk>
