# $OpenBSD$

COMMENT =	perl easy access to SQLite databases using objects

DISTNAME =	DBIx-SQLite-Simple-0.34
CATEGORIES =	databases

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl artistic license
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

BUILD_DEPENDS =		${RUN_DEPENDS}
RUN_DEPENDS =		databases/p5-DBD-SQLite

MODCPAN_EXAMPLES =	Yes

.include <bsd.port.mk>
