# $OpenBSD: Makefile,v 1.5 2011/01/03 08:25:17 jasper Exp $

COMMENT =	object oriented interface to create salted hashes

MODULES =	cpan
DISTNAME =	Crypt-SaltedHash-0.06
CATEGORIES =	security
USE_GROFF =	Yes

MAINTAINER =	Jim Razmus II <jim@bonetruck.org>

CPAN_AUTHOR =	ESSKAR

# Perl
PERMIT_PACKAGE_CDROM =	Yes

.include <bsd.port.mk>
