# $OpenBSD: Makefile,v 1.4 2011/01/02 19:32:50 benoit Exp $

COMMENT =	object oriented interface to create salted hashes

MODULES =	cpan
DISTNAME =	Crypt-SaltedHash-0.06
CATEGORIES =	security
REVISION =	0

USE_GROFF =	Yes

MAINTAINER =	Jim Razmus II <jim@bonetruck.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes
PERMIT_PACKAGE_FTP =	Yes
PERMIT_DISTFILES_CDROM =Yes
PERMIT_DISTFILES_FTP =	Yes

CPAN_AUTHOR =	ESSKAR

.include <bsd.port.mk>
