# $OpenBSD$

COMMENT =	IO::Socket with read/write timeout

DISTNAME =	IO-Socket-Timeout-0.27
CATEGORIES =	net

MAINTAINER =	Benoit Lecocq <benoit@openbsd.org>

# Perl
PERMIT_PACKAGE_CDROM =	Yes

MODULES =		cpan

# XXX -> Module to create
# TEST_DEPENDS =	devel/p5-PerlIO-via-Timeout

.include <bsd.port.mk>
