# $OpenBSD$

COMMENT =		ooc object-oriented programming language

DISTNAME =		ooc-src-0.2
PKGNAME =		ooc-0.2
CATEGORIES =		lang

HOMEPAGE =		http://ooc-lang.org/

MAINTAINER =		Benoit Lecocq <benoit@openbsd.org>

# In case of GPL, version number must be appended (e.g. v2, v2+, v3).
PERMIT_PACKAGE_CDROM =	Yes

MASTER_SITES =		http://ooc-language.googlecode.com/files/

EXTRACT_SUFX =		.tar.bz2

.include <bsd.port.mk>
