# $OpenBSD: Makefile,v 1.7 2011/01/02 13:31:53 benoit Exp $

COMMENT=	read tags of MP3 audio files

MODULES=	cpan
DISTNAME=	MP3-Tag-1.13
CATEGORIES=	audio

MAINTAINER=	Andreas Bihlmaier <andreas.bihlmaier@gmx.de>
USE_GROFF =	Yes

# perl
PERMIT_PACKAGE_CDROM=	Yes

.include <bsd.port.mk>
