# $OpenBSD: Makefile,v 1.6 2007/09/16 02:53:00 merdely Exp $

COMMENT=	library for balanced binary trees

VERSION=	2.0.2a
DISTNAME=	avl-${VERSION}
PKGNAME=	libavl-${VERSION}
CATEGORIES=	devel

HOMEPAGE=	http://www.stanford.edu/~blp/avl/

MAINTAINER=	Kevin Lo <kevlo@openbsd.org>

# GPLv2
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

MASTER_SITES=   ${MASTER_SITE_GNU:=avl/}

USE_GMAKE=	Yes

.include <bsd.port.mk>
