# $OpenBSD$

COMMENT =	library for manipulating PDF documents
VERSION=	0.4.5
DISTNAME=	pdfedit-${VERSION}
CATEGORIES=	textproc

HOMEPAGE=	http://pdfedit.petricek.net/

MAINTAINER=	Benoit Lecocq <benoit@openbsd.org>

# GPLv2
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=pdfedit/}

WANTLIB=	c

USE_GMAKE =	Yes

.include <bsd.port.mk>
